"use client";
import { useState } from "react";
const API = "https://earthwatch.onrender.com";
export default function ClimateReportPDF() {
  const [loading, setLoading] = useState(false);
  const [city, setCity] = useState("Delhi");
  const generateReport = async () => {
    setLoading(true);
    try {
      const [temp, co2, aqi, climate, tipping] = await Promise.all([
        fetch(`${API}/api/temperature`).then(r => r.json()),
        fetch(`${API}/api/co2`).then(r => r.json()),
        fetch(`${API}/api/air-quality`).then(r => r.json()),
        fetch(`${API}/api/climate-index`).then(r => r.json()),
        fetch(`${API}/api/tipping-points`).then(r => r.json()),
      ]);
      const now = new Date().toLocaleString();
      const html = `
<!DOCTYPE html><html><head><style>
body{font-family:Arial,sans-serif;margin:40px;color:#111;max-width:800px}
h1{color:#16a34a;border-bottom:2px solid #16a34a;padding-bottom:10px}
h2{color:#374151;margin-top:30px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:16px 0}
.card{border:1px solid #d1d5db;border-radius:8px;padding:16px}
.value{font-size:2em;font-weight:bold;color:#16a34a}
.red{color:#ef4444}.orange{color:#f97316}.label{color:#6b7280;font-size:0.85em}
table{width:100%;border-collapse:collapse;margin-top:10px}
th{background:#f3f4f6;padding:8px;text-align:left}td{padding:8px;border-bottom:1px solid #e5e7eb}
</style></head><body>
<h1>EarthWatch Climate Report</h1>
<p class="label">Generated: ${now} | Location: ${city}</p>
<h2>Current Conditions</h2>
<div class="grid">
  <div class="card"><div class="label">Temperature</div><div class="value">${temp.current_temperature ?? "--"}°C</div></div>
  <div class="card"><div class="label">CO2 Level</div><div class="value red">${co2.latest_co2_ppm ?? "--"} ppm</div></div>
  <div class="card"><div class="label">Air Quality Index</div><div class="value orange">${aqi.current_aqi ?? "--"}</div><div>${aqi.aqi_label ?? ""}</div></div>
  <div class="card"><div class="label">El Nino/La Nina</div><div class="value">${climate.latest?.phase ?? "--"}</div><div>ONI: ${climate.latest?.oni ?? "--"}</div></div>
</div>
<h2>Climate Tipping Points</h2>
<table><tr><th>Threshold</th><th>Current</th><th>Limit</th><th>Status</th></tr>
${tipping.tipping_points?.map((t: any) => `<tr><td>${t.name}</td><td>${t.current} ${t.unit}</td><td>${t.threshold} ${t.unit}</td><td style="color:${t.status==='exceeded'?'#ef4444':'#16a34a'}">${t.status.toUpperCase()}</td></tr>`).join("") ?? ""}
</table>
<p style="margin-top:40px;color:#9ca3af;font-size:0.8em">Generated by EarthWatch — Real-Time Climate Intelligence Platform<br>Data sources: Open-Meteo, NOAA, NASA POWER, GDACS</p>
</body></html>`;
      const blob = new Blob([html], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = `earthwatch_report_${city}_${Date.now()}.html`;
      a.click(); URL.revokeObjectURL(url);
    } catch (e) { alert("Report generation failed!"); }
    finally { setLoading(false); }
  };
  return (
    <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 mb-8">
      <h2 className="text-xl font-bold text-white mb-1">Climate Report Generator (HTML)</h2>
      <p className="text-gray-500 text-xs mb-4">Download complete climate report as HTML file (open in browser to print as PDF)</p>
      <div className="flex gap-3">
        <input value={city} onChange={e => setCity(e.target.value)} placeholder="City name" className="flex-1 bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-green-500" />
        <button onClick={generateReport} disabled={loading} className="bg-green-700 hover:bg-green-600 disabled:bg-gray-700 text-white font-bold px-5 py-2 rounded-lg text-sm">
          {loading ? "Generating..." : "Download Report"}
        </button>
      </div>
      <p className="text-gray-600 text-xs mt-2">Includes: Temperature, CO2, AQI, El Nino status, Tipping Points</p>
    </div>
  );
}
